name: Treesearch build and deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      test-value:
        required: true
        type: string
    secrets:
      passed-secret:
        required: true
jobs:
  build:
    name: ${{ inputs.environment }}-${{ secrets.passed-secret }}-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3