name: Treesearch build and deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      passed-var:
        required: false
        type: string
    secrets:
      passed_secret:
        required: false
jobs:
  build:
    name: ${{ inputs.environment }}-${{ inputs.passed-var }}-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3