name: Prod build deploy

on:
  push:
    branches:
      - main

jobs:
  main_build_deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
      passed-var: ${{ vars.TEST_VAR_PROD }}
    secrets:
      passed_secret: ${{ secrets.TEST_SECRET}}

  dev_build_deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      passed-var: ${{ vars.TEST_VAR_DEV }}
    secrets:
      passed_secret: ${{ secrets.TEST_SECRET}}

      