name: Prod build deploy

on:
  push:
    branches:
      - main

jobs:
  develop_build_deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
      test-value: ${{secrets[github.event.inputs.TEST_SECRET]}}